# src/backend/access/blockchain/Makefile

subdir = src/backend/access/blockchain
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = blockchainam.o

include $(top_srcdir)/src/backend/common.mk
